### ISSUE TITLE
Fix extra white space in list.md

### ISSUE THREAD

**Issue by tushparte** [opencodeiiita/Opencode-Collaborative-20#353]
check 1.

**Comment by aarpit1010** [comment]
claim

**Comment by sarthakm21** [comment]
claim

**Comment by aarpit1010** [comment]
@niftyy  Sir, the changes had already been made in the PR#354 that I closed. Since, I deleted the repo and tried to do the task again, it had already been corrected. So, there was nothing for me to commit. The extra white space issue has already been fixed. How will I get points for this issue then ?

![Screenshot (42)](https://user-images.githubusercontent.com/58038078/73919327-55115300-48e9-11ea-9ac7-f39f5aa5e574.png)

**Comment by tushparte** [comment]
somebody else has fixed it already so this issue will be closed.
